In [ ]:
'''NumPy is a Python package. It stands for 'Numerical Python'. 
It is a library consisting of multidimensional array objects and a collection of routines for processing of array.
There are many contributors to this open source project.
'''

In [ ]:
'''
Python List:

1.Able to store different data types in the same list
2.Storing each item in random location in the memory
3.Good for the scenario where list can grow dynamically
4.Inbuilt data type.
5.It has more inbuilt functions
6.Appending will take less time in O(1) time

NumPy Array:

1.Can store only one data type in an array at any time
2.Storing each item is sequential which makes array more effective in processing.
3.Good for the scenario where the items are fixed size and same data time
4.Need to install external library NumPy
5.No extra functions, so it will not more memory store.
6.Appending elements will take more time in O(N) time
'''

In [1]:
#!pip install numpy

In [2]:
#!pip install numpy
import numpy as np 
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [3]:
# more than one dimensions 
import numpy as np 
a = np.array([[1, 2], [3, 4]]) 
a

array([[1, 2],
       [3, 4]])

In [5]:
# minimum dimensions 

a = np.array([1, 2, 3,4,5], ndmin = 4) 
a

array([[[[1, 2, 3, 4, 5]]]])

In [6]:
# dtype parameter 

a = np.array([1, 2, 3], dtype = int) 
a

array([1, 2, 3])

In [7]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [11]:
s=np.array([1,2,3,4,5])  # 6 2*3 3*2     #task 37 shape reshape odd(reshape solution) even odd
s.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print(a)
a.shape
b = a.reshape(3,2) 
b

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(1,10,2) 
b=np.arange(1,20)
print(a)
b

[1 3 5 7 9]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(10) 
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
import numpy as np 
import warnings
warnings.filterwarnings('ignore')
x = np.zeros((9), dtype = int) 
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
x

array([1., 1., 1., 1., 1.])

In [21]:
import numpy as np 
x = np.ones([2,3], dtype = int) 
x

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
# convert list to ndarray 
import numpy as np 

x = [1,2.2,'python'] 
a = np.asarray(x) 
a

array(['1', '2.2', 'python'], dtype='<U32')

In [23]:
# ndarray from list of tuples 
import numpy as np 

x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [24]:
import numpy as np 
x = np.arange(0,5,2) 
x

array([0, 2, 4])

In [25]:
import numpy as np 
# dtype set 
x = np.arange(5, dtype = float)
x

array([0., 1., 2., 3., 4.])

In [26]:
import numpy as np 
a = np.arange(10)
print(a)
s = slice(2,7,2) 
a[s]


[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [27]:
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
b

array([2, 4, 6])

In [31]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a + b 
c

array([11, 22, 33, 44])

In [34]:
import numpy as np
a = np.arange(0,60,5)
print(a.shape)
print(a)
a = a.reshape(3,4)
print(a.shape)
z=a.ravel()
print(z.shape)

print('Original array is:')
print(a)
print('\n')

print('Modified array is:')
for x in np.nditer(a):
   print(x)


(12,)
[ 0  5 10 15 20 25 30 35 40 45 50 55]
(3, 4)
(12,)
Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [35]:
import numpy as np 
a = np.array([0,30,45,60,90]) 

print('Sine of different angles:')
# Convert to radians by multiplying with pi/180 
print(np.sin(a))
print('\n') 

print('Cosine values for angles in array:')
print(np.cos(a*np.pi/180) )
print('\n')  

print('Tangent values for given angles:')
print(np.tan(a*np.pi/180))


Sine of different angles:
[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [42]:
import numpy as np 
a = np.arange(9, dtype = np.float).reshape(3,3) 

print('First array:') 
print(a) 
print('\n')  

print('Second array:')
b = np.array([1,2,3]) 
print(b)
print('\n')  

print('Add the two arrays:') 
print(np.add(a,b)) 
print('\n')  

print('Subtract the two arrays:' )
print(np.subtract(a,b) )
print('\n')  

print('Multiply the two arrays:' )
print(np.multiply(a,b)) 
print('\n')  

print('Divide the two arrays:' )
print(np.divide(a,b))

First array:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array:
[1 2 3]


Add the two arrays:
[[ 1.  3.  5.]
 [ 4.  6.  8.]
 [ 7.  9. 11.]]


Subtract the two arrays:
[[-1. -1. -1.]
 [ 2.  2.  2.]
 [ 5.  5.  5.]]


Multiply the two arrays:
[[ 0.  2.  6.]
 [ 3.  8. 15.]
 [ 6. 14. 24.]]


Divide the two arrays:
[[0.         0.5        0.66666667]
 [3.         2.         1.66666667]
 [6.         3.5        2.66666667]]


In [46]:
import numpy as np 
a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

print('Our array is:') 
print(a ) 
print('\n')


print('Applying amin() function again:' )
print(np.amin(a,0) )
print('\n' )


print('Applying amax() function again:')
print(np.amax(a, axis = 1))
print(np.amax(a))

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function again:
[2 4 3]


Applying amax() function again:
[7 8 9]
9


In [47]:
import numpy as np  
a = np.array([[3,7],[9,1]]) 

print('Our array is:') 
print(a)
print('\n')

print('Applying sort() function:')
print(np.sort(a)) 
print('\n') 
  
print('Sort along axis 0:') 
print(np.sort(a, axis = 0))
print('\n')  


Our array is:
[[3 7]
 [9 1]]


Applying sort() function:
[[3 7]
 [1 9]]


Sort along axis 0:
[[3 1]
 [9 7]]




In [53]:
import numpy as np
  
arr = np.array([1,2,3], dtype = float)
  
g = arr.itemsize
  
g

8

In [54]:

# numpy.sqrt() method

# importing numpy
import numpy as k

# applying sqrt() method on integer numbers
arr1 = k.sqrt([1, 4, 9, 16])
arr2 = k.sqrt([6, 10, 18])

print("square-root of an array1 : ", arr1)
print("square-root of an array2 : ", arr2)


square-root of an array1 :  [1. 2. 3. 4.]
square-root of an array2 :  [2.44948974 3.16227766 4.24264069]


In [56]:
# Python Program illustrating
# numpy.sum() method
import numpy as np
# 1D array
arr = [20, 2, .2, 10, 4]

print("\nSum of arr : ", np.sum(arr))

print("Sum of arr(uint8) : ", np.sum(arr, dtype = int))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))





Sum of arr :  36.2
Sum of arr(uint8) :  36
Sum of arr(float32) :  36.2


In [57]:

# numpy.sum() method
import numpy as np
# 2D array
arr = [[14, 17, 12, 33, 44],[15, 6, 27, 8, 19],[23, 2, 54, 1, 4,]]

print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0))
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1))





Sum of arr :  279
Sum of arr(axis = 0) :  [52 25 93 42 67]
Sum of arr(axis = 1) :  [120  75  84]


In [ ]:
#task 38
numpy practise
#task 39
time complex
#task 40
arrays random
